name: zeehub_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  csv: ^5.1.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  sizer_pro: ^2.2.0
  spreadsheet_decoder: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
   - assets/meterImage.png
